In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("titanic1.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [ ]:
inputs=df.drop('Survived',axis='columns')
target=df.Survived

In [ ]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [ ]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male  female  male
0       3    male  22.0   7.2500       0     1       0     1
1       1  female  38.0  71.2833       1     0       1     0
2       3  female  26.0   7.9250       1     0       1     0

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female  female
0       3  22.0   7.2500       0       0
1       1  38.0  71.2833       1       1
2       3  26.0   7.9250       1       1

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female  female
0       3  22.0   7.2500       0       0
1       1  38.0  71.2833       1       1
2       3  26.0   7.9250       1       1
3       1  35.0  53.1000       1       1
4       3  35.0   8.0500       0       0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
model.score(x_test,y_test)

0.7761194029850746

In [ ]:
x_test[0:10]

     Pclass   Age     Fare  female  female
339       1  45.0  35.5000       0       0
567       3  29.0  21.0750       1       1
117       2  29.0  21.0000       0       0
20        2  35.0  26.0000       0       0
607       1  27.0  30.5000       0       0
213       2  30.0  13.0000       0       0
365       3  30.0   7.2500       0       0
860       3  41.0  14.1083       0       0
206       3  32.0  15.8500       0       0
741       1  36.0  78.8500       0       0

In [ ]:
y_test[0:10]

339    0
567    0
117    0
20     0
607    1
213    0
365    0
860    0
206    0
741    0
Name: Survived, dtype: int64

In [ ]:
model.predict(x_test[0:10])

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
model.predict_proba(x_test[:10])

array([[0.89769862, 0.10230138],
       [0.10772952, 0.89227048],
       [0.98234541, 0.01765459],
       [0.98186491, 0.01813509],
       [0.91170952, 0.08829048],
       [0.98277163, 0.01722837],
       [0.9933225 , 0.0066775 ],
       [0.99310527, 0.00689473],
       [0.99345108, 0.00654892],
       [0.71212819, 0.28787181]])

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train,y_train)

array([0.8       , 0.728     , 0.752     , 0.81451613, 0.80645161])